//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by plugin.rc
//
#define IDS_ABOUT_STRING                1
#define IDS_SZ_MENU_NAV_TOOLTIP         2
#define ID_DOCS                         3
#define IDS_UNTITLED_MENU_ITEM          3
#define IDLEFT                          4
#define IDS_UNTITLED_MENU               4
#define ID_WEB                          5
#define IDS_ON                          5
#define IDRIGHT                         6
#define IDS_OFF                         6
#define ID_DEFAULTS                     7
#define IDS_USE_UP_DOWN_ARROW_KEYS      7
#define ID_MSG                          8
#define IDS_CURRENT_VALUE_OF_X          8
#define ID_SPRITE                       9
#define IDS_LOAD_FROM_FILE              9
#define IDS_SAVE_TO_FILE                10
#define IDS_ENTER_THE_NEW_STRING        11
#define IDS_MILKDROP_ERROR              12
#define IDS_MILKDROP_WARNING            13
#define IDS_ERROR_CREATING_DOUBLE_SIZED_D3DX_TITLE_FONT 14
#define IDS_DESKTOP_NOT_SUPPORTED       14
#define IDS_RATING                      15
#define IDS_DISABLED                    16
#define IDS_ARE_YOU_SURE_YOU_WANT_TO_DELETE_PRESET 17
#define IDS_PRESET_TO_DELETE            18
#define IDS_FILE_ALREADY_EXISTS_OVERWRITE_IT 19
#define IDS_FILE_IN_QUESTION_X_MILK     20
#define IDS_ERROR_NO_PRESET_FILE_FOUND_IN_X_MILK 21
#define IDS_LOAD_WHICH_PRESET_PLUS_COMMANDS 22
#define IDS_PAGE_X_OF_X                 23
#define IDS_LOCKED                      24
#define IDS_ILLEGAL_CHARACTER           25
#define IDS_STRING_TOO_LONG             26
#define IDS_DIRECTORY_TO_JUMP_TO        27
#define IDS_ERROR_IMPORTING_BAD_FILENAME 28
#define IDS_ERROR_IMPORTING_BAD_FILENAME_OR_NOT_OVERWRITEABLE 29
#define IDS_INVALID_PATH                30
#define IDS_ENTER_THE_NEW_NAME_FOR_X    31
#define IDS_PRESET_ORDER_IS_NOW_X       32
#define IDS_SEQUENTIAL                  33
#define IDS_RANDOM                      34
#define IDS_SAVE_AS                     35
#define IDS_AUTO                        36
#define IDS_8X6_FAST                    37
#define IDS_16X12_FAST                  38
#define IDS_24X18                       39
#define IDS_32X24                       40
#define IDS_40X30                       41
#define IDS_48X36_DEFAULT               42
#define IDS_64X48_SLOW                  43
#define IDS_80X60_SLOW                  44
#define IDS_96X72_SLOW                  45
#define IDS_128X96_SLOW                 46
#define IDS_ERROR_IN_SHELLEXECUTE       47
#define IDS_MESH_SIZE                   47
#define IDS_MESH_SIZE_TEXT              48
#define IDS_CB_ALWAYS3D                 49
#define IDS_DISABLE_PRESET_RATING       50
#define IDS_DISABLE_PRESET_RATING_TEXT  51
#define IDS_CB_NOWARN2                  52
#define IDS_START_WITH_PRESET_LOCK_ON   53
#define IDS_START_WITH_PRESET_LOCK_ON_TEXT 54
#define IDS_BRIGHT_SLIDER               55
#define IDS_CB_AUTOGAMMA                56
#define IDS_SPRITE                      57
#define IDS_MSG                         58
#define IDS_SONGTITLEANIM_DURATION_TEXT 59
#define IDS_RAND_TITLE_TEXT             60
#define IDS_RAND_MSG_TEXT               61
#define IDS_TITLE_ANIMS_TEXT            62
#define IDS_BETWEEN_TIME_TEXT           63
#define IDS_BETWEEN_TIME_RANDOM_TEXT    64
#define IDS_BLEND_AUTO_TEXT             65
#define IDS_BLEND_USER_TEXT             66
#define IDS_HARDCUT_BETWEEN_TIME_TEXT   67
#define IDS_HARDCUT_LOUDNESS_TEXT       68
#define IDS_CB_HARDCUTS                 69
#define IDS_EDIT_CURRENT_PRESET         70
#define IDS_MOTION                      71
#define IDS_DRAWING_CUSTOM_SHAPES       72
#define IDS_DRAWING_CUSTOM_WAVES        73
#define IDS_DRAWING_SIMPLE_WAVEFORM     74
#define IDS_DRAWING_BORDERS_MOTION_VECTORS 75
#define IDS_POST_PROCESSING_MISC        76
#define IDS_CUSTOM_WAVE_X               77
#define IDS_CUSTOM_SHAPE_X              78
#define IDS_MENU_EDIT_PRESET_INIT_CODE  79
#define IDS_MENU_EDIT_PRESET_INIT_CODE_TT 80
#define IDS_MENU_EDIT_PER_FRAME_EQUATIONS 81
#define IDS_MENU_EDIT_PER_FRAME_EQUATIONS_TT 82
#define IDS_MENU_WAVE_TYPE              83
#define IDS_MENU_WAVE_TYPE_TT           84
#define IDS_MENU_SIZE                   85
#define IDS_MENU_SIZE_TT                86
#define IDS_MENU_SMOOTH                 87
#define IDS_MENU_SMOOTH_TT              88
#define IDS_MENU_MYSTERY_PARAMETER      89
#define IDS_MENU_MYSTERY_PARAMETER_TT   90
#define IDS_MENU_POSITION_X             91
#define IDS_MENU_POSITION_X_TT          92
#define IDS_MENU_POSITION_Y             93
#define IDS_MENU_POSITION_Y_TT          94
#define IDS_MENU_COLOR_RED              95
#define IDS_MENU_COLOR_RED_TT           96
#define IDS_MENU_COLOR_GREEN            97
#define IDS_MENU_COLOR_GREEN_TT         98
#define IDS_MENU_COLOR_BLUE             99
#define IDS_MENU_COLOR_BLUE_TT          100
#define IDD_DIALOG1                     101
#define IDD_CONFIG                      101
#define IDS_MENU_OPACITY                101
#define IDD_PROPPAGE_1                  102
#define IDS_MENU_OPACITY_TT             102
#define IDD_PROPPAGE_2                  103
#define IDS_MENU_USE_DOTS               103
#define IDS_MENU_USE_DOTS_TT            104
#define IDS_MENU_DRAW_THICK             105
#define IDS_MENU_DRAW_THICK_TT          106
#define IDS_MENU_MODULATE_OPACITY_BY_VOLUME 107
#define IDS_MENU_MODULATE_OPACITY_BY_VOLUME_TT 108
#define IDS_MENU_MODULATION_TRANSPARENT_VOLUME 109
#define IDR_WINDOWED_CONTEXT_MENU       110
#define IDS_MENU_MODULATION_TRANSPARENT_VOLUME_TT 110
#define IDS_MENU_MODULATION_OPAQUE_VOLUME 111
#define IDS_MENU_MODULATION_OPAQUE_VOLUME_TT 112
#define IDS_MENU_ADDITIVE_DRAWING       113
#define IDD_PROPPAGE_3                  114
#define IDS_MENU_ADDITIVE_DRAWING_TT    114
#define IDD_PROPPAGE_4                  115
#define IDS_MENU_COLOR_BRIGHTENING      115
#define IDD_PROPPAGE_5                  116
#define IDS_MENU_COLOR_BRIGHTENING_TT   116
#define IDD_PROPPAGE_6                  117
#define IDS_MENU_OUTER_BORDER_THICKNESS 117
#define IDD_PROPPAGE_7                  118
#define IDS_MENU_OUTER_BORDER_THICKNESS_TT 118
#define IDD_PROPPAGE_8                  119
#define IDS_MENU_COLOR_RED_OUTER        119
#define IDI_PLUGIN_ICON                 120
#define IDS_MENU_COLOR_RED_OUTER_TT     120
#define IDD_FONTDIALOG                  121
#define IDS_MENU_COLOR_GREEN_OUTER      121
#define IDD_DESKTOPMODE                 122
#define IDS_MENU_COLOR_GREEN_OUTER_TT   122
#define IDD_DUALHEAD                    123
#define IDS_MENU_COLOR_BLUE_OUTER       123
#define IDS_MENU_COLOR_BLUE_OUTER_TT    124
#define IDS_MENU_OPACITY_OUTER          125
#define IDS_MENU_OPACITY_OUTER_TT       126
#define IDS_MENU_INNER_BORDER_THICKNESS 127
#define IDS_MENU_INNER_BORDER_THICKNESS_TT 128
#define IDR_TEXT1                       129
#define IDS_MENU_COLOR_RED_INNER_TT     129
#define IDR_TEXT2                       130
#define IDS_MENU_COLOR_GREEN_INNER_TT   130
#define IDR_GZ1                         131
#define IDR_TEXT_GZ                     131
#define IDS_MENU_COLOR_BLUE_INNER_TT    131
#define IDS_MENU_OPACITY_INNER_TT       132
#define IDS_MENU_MOTION_VECTOR_OPACITY  133
#define IDS_MENU_MOTION_VECTOR_OPACITY_TT 134
#define IDS_MENU_NUM_MOT_VECTORS_X      135
#define IDS_MENU_NUM_MOT_VECTORS_X_TT   136
#define IDS_MENU_NUM_MOT_VECTORS_Y      137
#define IDS_MENU_NUM_MOT_VECTORS_Y_TT   138
#define IDS_MENU_OFFSET_X               139
#define IDS_MENU_OFFSET_X_TT            140
#define IDS_MENU_OFFSET_Y               141
#define IDS_MENU_OFFSET_Y_TT            142
#define IDS_MENU_TRAIL_LENGTH           143
#define IDS_MENU_TRAIL_LENGTH_TT        144
#define IDS_MENU_COLOR_RED_MOTION_VECTOR_TT 145
#define IDS_MENU_COLOR_GREEN_MOTION_VECTOR_TT 146
#define IDS_MENU_COLOR_BLUE_MOTION_VECTOR_TT 147
#define IDS_MENU_ZOOM_AMOUNT            148
#define IDS_MENU_ZOOM_AMOUNT_TT         149
#define IDS_MENU_ZOOM_EXPONENT          150
#define IDS_MENU_ZOOM_EXPONENT_TT       151
#define IDS_MENU_WARP_AMOUNT            152
#define IDS_MENU_WARP_AMOUNT_TT         153
#define IDS_MENU_WARP_SCALE             154
#define IDS_MENU_WARP_SCALE_TT          155
#define IDS_MENU_WARP_SPEED             156
#define IDS_MENU_WARP_SPEED_TT          157
#define IDS_MENU_ROTATION_AMOUNT        158
#define IDS_MENU_ROTATION_AMOUNT_TT     159
#define IDS_MENU_ROTATION_CENTER_OF_X   160
#define IDS_MENU_ROTATION_CENTER_OF_X_TT 161
#define IDS_MENU_ROTATION_CENTER_OF_Y   162
#define IDS_MENU_ROTATION_CENTER_OF_Y_TT 163
#define IDS_MENU_TRANSLATION_X          164
#define IDS_MENU_TRANSLATION_X_TT       165
#define IDS_MENU_TRANSLATION_Y          166
#define IDS_MENU_TRANSLATION_Y_TT       167
#define IDS_MENU_SCALING_X              168
#define IDS_MENU_SCALING_X_TT           169
#define IDS_MENU_SCALING_Y              170
#define IDS_MENU_SCALING_Y_TT           171
#define IDS_MENU_SUSTAIN_LEVEL          172
#define IDS_MENU_SUSTAIN_LEVEL_TT       173
#define IDS_MENU_DARKEN_CENTER          174
#define IDS_MENU_DARKEN_CENTER_TT       175
#define IDS_MENU_GAMMA_ADJUSTMENT       176
#define IDS_MENU_GAMMA_ADJUSTMENT_TT    177
#define IDS_MENU_HUE_SHADER             178
#define IDS_MENU_HUE_SHADER_TT          179
#define IDS_MENU_VIDEO_ECHO_ALPHA       180
#define IDS_MENU_VIDEO_ECHO_ALPHA_TT    181
#define IDS_MENU_VIDEO_ECHO_ZOOM        182
#define IDS_MENU_VIDEO_ECHO_ZOOM_TT     183
#define IDS_MENU_VIDEO_ECHO_ORIENTATION 184
#define IDS_MENU_VIDEO_ECHO_ORIENTATION_TT 185
#define IDS_MENU_TEXTURE_WRAP           186
#define IDS_MENU_TEXTURE_WRAP_TT        187
#define IDS_MENU_FILTER_INVERT          188
#define IDS_MENU_FILTER_INVERT_TT       189
#define IDS_MENU_FILTER_BRIGHTEN        190
#define IDS_MENU_FILTER_BRIGHTEN_TT     191
#define IDS_MENU_FILTER_DARKEN          192
#define IDS_MENU_FILTER_DARKEN_TT       193
#define IDS_MENU_FILTER_SOLARIZE        194
#define IDS_MENU_FILTER_SOLARIZE_TT     195
#define IDS_MENU_ENABLED                196
#define IDS_MENU_ENABLED_TT             197
#define IDS_MENU_NUMBER_OF_SAMPLES      198
#define IDS_MENU_NUMBER_OF_SAMPLES_TT   199
#define IDS_MENU_L_R_SEPARATION         200
#define IDS_MENU_L_R_SEPARATION_TT      201
#define IDS_MENU_SCALING                202
#define IDS_MENU_SCALING_TT             203
#define IDS_MENU_SMOOTHING_TT           204
#define IDS_MENU_OPACITY_WAVE_TT        205
#define IDS_MENU_USE_SPECTRUM           206
#define IDS_MENU_USE_SPECTRUM_TT        207
#define IDS_MENU_USE_DOTS_WAVE_TT       208
#define IDS_MENU_DRAW_THICK_WAVE_TT     209
#define IDS_MENU_ADDITIVE_DRAWING_WAVE_TT 210
#define IDS_MENU_EXPORT_TO_FILE         211
#define IDS_MENU_EXPORT_TO_FILE_TT      212
#define IDS_MENU_IMPORT_FROM_FILE       213
#define IDS_MENU_IMPORT_FROM_FILE_TT    214
#define IDS_MENU_EDIT_INIT_CODE         215
#define IDS_MENU_EDIT_INIT_CODE_TT      216
#define IDS_MENU_EDIT_PER_FRAME_CODE    217
#define IDS_MENU_EDIT_PER_FRAME_CODE_TT 218
#define IDS_MENU_EDIT_PER_POINT_CODE    219
#define IDS_MENU_EDIT_PER_POINT_CODE_TT 220
#define IDS_MENU_ENABLED_SHAPE_TT       221
#define IDS_MENU_NUMBER_OF_SIDES        222
#define IDS_MENU_NUMBER_OF_SIDES_TT     223
#define IDS_MENU_DRAW_THICK_SHAPE_TT    224
#define IDS_MENU_ADDITIVE_DRAWING_SHAPE_TT 225
#define IDS_MENU_X_POSITION             226
#define IDS_MENU_X_POSITION_TT          227
#define IDS_MENU_Y_POSITION             228
#define IDS_MENU_Y_POSITION_TT          229
#define IDS_MENU_RADIUS                 230
#define IDS_MENU_RADIUS_TT              231
#define IDS_MENU_ANGLE                  232
#define IDS_MENU_ANGLE_TT               233
#define IDS_MENU_TEXTURED               234
#define IDS_MENU_TEXTURED_TT            235
#define IDS_MENU_TEXTURE_ZOOM           236
#define IDS_MENU_TEXTURE_ZOOM_TT        237
#define IDS_MENU_TEXTURE_ANGLE          238
#define IDS_MENU_TEXTURE_ANGLE_TT       239
#define IDS_MENU_INNER_COLOR_RED        240
#define IDS_MENU_INNER_COLOR_RED_TT     241
#define IDS_MENU_INNER_COLOR_GREEN      242
#define IDS_MENU_INNER_COLOR_GREEN_TT   243
#define IDS_MENU_INNER_COLOR_BLUE       244
#define IDS_MENU_INNER_COLOR_BLUE_TT    245
#define IDS_MENU_INNER_OPACITY          246
#define IDS_MENU_INNER_OPACITY_TT       247
#define IDS_MENU_OUTER_COLOR_RED        248
#define IDS_MENU_OUTER_COLOR_RED_TT     249
#define IDS_MENU_OUTER_COLOR_GREEN      250
#define IDS_MENU_OUTER_COLOR_GREEN_TT   251
#define IDS_MENU_OUTER_COLOR_BLUE       252
#define IDS_MENU_OUTER_COLOR_BLUE_TT    253
#define IDS_MENU_OUTER_OPACITY          254
#define IDS_MENU_OUTER_OPACITY_TT       255
#define IDS_MENU_BORDER_COLOR_RED       256
#define IDS_MENU_BORDER_COLOR_RED_TT    257
#define IDS_MENU_BORDER_COLOR_GREEN     258
#define IDS_MENU_BORDER_COLOR_GREEN_TT  259
#define IDS_MENU_BORDER_COLOR_BLUE      260
#define IDS_MENU_BORDER_COLOR_BLUE_TT   261
#define IDS_MENU_BORDER_OPACITY         262
#define IDS_MENU_BORDER_OPACITY_TT      263
#define IDS_MENU_EXPORT_TO_FILE_SHAPE_TT 264
#define IDS_MENU_IMPORT_FROM_FILE_SHAPE_TT 265
#define IDS_ERROR_UNABLE_TO_SAVE_THE_FILE 266
#define IDS_SAVE_SUCCESSFUL             267
#define IDS_ERROR_UNABLE_TO_DELETE_THE_FILE 268
#define IDS_PRESET_X_DELETED            269
#define IDS_ERROR_A_FILE_ALREADY_EXISTS_WITH_THAT_FILENAME 270
#define IDS_ERROR_UNABLE_TO_RENAME_FILE 271
#define IDS_RENAME_SUCCESSFUL           272
#define IDS_SPRITE_X_WARNING_ERROR_IN_INIT_CODE 273
#define IDS_SPRITE_X_WARNING_ERROR_IN_PER_FRAME_CODE 274
#define IDS_SPRITE_X_ERROR_BAD_SLOT_INDEX 275
#define IDS_SPRITE_X_ERROR_IMAGE_FILE_MISSING_OR_CORRUPT 276
#define IDS_SPRITE_X_ERROR_OUT_OF_MEM   277
#define IDS_WARNING_PRESET_X_ERROR_IN_WAVE_X_INIT_CODE 278
#define IDS_WARNING_PRESET_X_ERROR_IN_WAVE_X_PER_FRAME_CODE 279
#define IDS_WARNING_PRESET_X_ERROR_IN_WAVE_X_PER_POINT_CODE 280
#define IDS_WARNING_PRESET_X_ERROR_IN_SHAPE_X_INIT_CODE 281
#define IDS_WARNING_PRESET_X_ERROR_IN_SHAPE_X_PER_FRAME_CODE 282
#define IDS_CONFIG_PANEL_BUTTON_1       283
#define IDS_CONFIG_PANEL_BUTTON_2       284
#define IDS_CONFIG_PANEL_BUTTON_3       285
#define IDS_CONFIG_PANEL_BUTTON_4       286
#define IDS_EXTRA_FONT_1_NAME           287
#define IDS_EXTRA_FONT_2_NAME           288
#define IDS_PRESS_F1_MSG                289
#define IDS_UNKNOWN                     290
#define IDS_GRAPHICS_SUBSYSTEM_IS_TEMPORARILY_UNSTABLE 291
#define IDS_DISABLED_PAGE_TEARING       291
#define IDS_NONE                        292
#define IDS_UNLIMITED                   293
#define IDS_X_FRAME_SEC                 294
#define IDS_HELP_ON_X_BUTTON            295
#define IDS_FONTS_HELP                  296
#define IDS_DUAL_HEAD_HELP              297
#define IDS_MULTI_SAMPLING              298
#define IDS_MULTI_SAMPLING_HELP         299
#define IDS_MAX_FRAMERATE               300
#define IDS_MAX_FRAMERATE_HELP          301
#define IDS_FAKE_FULLSCREEN             302
#define IDS_FAKE_FULLSCREEN_HELP        303
#define IDS_FULLSCREEN_ADAPTER          304
#define IDS_FULLSCREEN_ADAPTER_HELP     305
#define IDS_WINDOWED_ADPATER            306
#define IDS_WINDOWED_ADPATER_HELP       307
#define IDS_DESKTOP_ADAPTER             308
#define IDS_DESKTOP_ADAPTER_HELP        309
#define IDS_HELP_ON_X_CHECKBOX          310
#define IDS_HELP_ON_X_CHECKBOX_HELP     311
#define IDS_FORCE_INTO_FS_MODE_HELP     312
#define IDS_FORCE_INTO_DESKTOP_MODE_HELP 313
#define IDS_HELP_ON_F1                  314
#define IDS_HELP_ON_F1_HELP             315
#define IDS_SAVE_CPU_CHECKBOX           316
#define IDS_SAVE_CPU_CHECKBOX_HELP      317
#define IDS_CB_SKIN_HELP                318
#define IDS_FS_DISPLAY_MODE             318
#define IDS_FS_DISPLAY_MODE_HELP        319
#define IDS_TRY_TO_FIX_SLOW_TEXT        320
#define IDS_TRY_TO_FIX_SLOW_TEXT_HELP   321
#define IDS_VJ_MODE                     322
#define IDS_VJ_MODE_HELP                323
#define IDS_HELP_ON_X                   324
#define IDS_DMS_LABEL_HELP              325
#define IDS_FS_LABEL_HELP               326
#define IDS_W_LABEL_HELP                327
#define IDS_CONFIG_PANEL_BUTTON_5       328
#define IDS_DM_MORE_HELP                328
#define IDS_CONFIG_PANEL_BUTTON_6       329
#define IDS_RESTORE_ALL_DEFAULTS        329
#define IDS_CONFIG_PANEL_BUTTON_7       330
#define IDS_RESTORE_ALL_DEFAULTS_TITLE  330
#define IDS_CONFIG_PANEL_BUTTON_8       331
#define IDS_INITCONFIG_FAILED           331
#define IDS_OK_HELP                     331
#define IDS_UNABLE_TO_LOAD_TABS         332
#define IDS_CANCEL_HELP                 332
#define IDS_DOCUMENTATION_FILE_NOT_FOUND 333
#define IDS_RESTORE_DEFAULTS_HELP       333
#define IDS_ACCESS_TO_DOCUMENTATION_FILE_DENIED 334
#define IDS_DOCUMENTATION_BUTTON_HELP   334
#define IDS_ACCESS_TO_DOCUMENTATION_FILE_FAILED_DUE_TO_NO_ASSOC 335
#define IDS_VIEW_ONLINE_DOCS_HELP       335
#define IDS_ACCESS_TO_DOCUMENTATION_FILE_FAILED_CODE_X 336
#define IDS_5_6_5_TEXTURE               336
#define IDS_ERROR_OPENING_DOCUMENTATION 337
#define IDS_5_5_5_TEXTURE               337
#define IDS_URL_COULD_NOT_OPEN          338
#define IDS_8_8_8_TEXTURE               338
#define IDS_ACCESS_TO_URL_WAS_DENIED    339
#define IDS_SPAN_BOTH_SCREENS           339
#define IDS_ACCESS_TO_URL_FAILED_DUE_TO_NO_ASSOC 340
#define IDS_USE_LEFT_SCREEN_ONLY        340
#define IDS_USE_RIGHT_SCREEN_ONLY       341
#define IDS_ACCESS_TO_URL_FAILED_CODE_X 342
#define IDS_USE_TOP_SCREEN_ONLY         342
#define IDS_ERROR_OPENING_URL           343
#define IDS_USE_BOTTOM_SCREEN_ONLY      343
#define IDS_UNABLE_TO_REGISTER_WINDOW_CLASS 344
#define IDS_DIRECTX_INIT_FAILED         345
#define IDS_DXC_ERR_CAPSFAIL            346
#define IDS_FS_DISPLAY_MODE_SELECTED_IS_INVALID 347
#define IDS_CREATEWINDOW_FAILED         348
#define IDS_TRYING_TO_ENTER_FS_MODE_WITH_MULTIPLE_DISPLAYS 349
#define IDS_TIP                         350
#define IDS_TRYING_TO_ENTER_FS_MODE_WITH_MULTIPLE_DISPLAYS_2 351
#define IDS_UNABLE_TO_CREATE_DIRECTX_DEVICE 352
#define IDS_DIRECTX_INIT_FAILED_X       353
#define IDS_NO_ALPHA_FALLBACK           354
#define IDS_WINDOW_RESIZE_FAILED        354
#define IDS_NO_ALPHA_FALLBACK_HELP      355
#define IDS_OUT_OF_VIDEO_MEMORY         355
#define IDS_CB_SHOW_ICONS_HELP          356
#define IDS_ERROR_LOADING_MAIN_MENU     356
#define IDS_CB_BOX                      357
#define IDS_ERROR_LOADING_CONTEXT_MENU  357
#define IDS_CB_BOX_HELP                 358
#define IDS_ERROR_CREATING_DIRECT3D_DEVICE_FOR_VJ_MODE 358
#define IDS_CB_MANUAL_SCOOT             359
#define IDS_VJ_MODE_INIT_ERROR          359
#define IDS_CB_MANUAL_SCOOT_HELP        360
#define IDS_ERROR_REGISTERING_WINDOW_CLASS_FOR_TEXT_WINDOW 360
#define IDS_ERROR_CREATING_VJ_WINDOW    361
#define IDS_OLDER_DISPLAY_ADAPTER_CATENATION 362
#define IDS_ERROR_CREATING_D3D_DEVICE_FOR_VJ_MODE 362
#define IDS_OLDER_DISPLAY_ADAPTER_CATENATION_2 363
#define IDS_ERROR_CREATING_D3DX_FONTS   363
#define IDS_UNABLE_TO_INIT_DXCONTEXT    364
#define IDS_TO_FREE_UP_SOME_MEMORY_RESTART_WINAMP_THEN_GO_TO_CONFIG_1 365
#define IDS_COULD_NOT_FIND_FILE_FOR_DESKTOP_MODE_X 366
#define IDS_TO_FREE_UP_SOME_MEMORY_RESTART_WINAMP_THEN_GO_TO_CONFIG_2 366
#define IDS_MILKDROP_ERROR_FILE_MISSING 367
#define IDS_TO_FREE_UP_SOME_MEMORY_RESTART_WINAMP_THEN_GO_TO_CONFIG_3 367
#define IDS_ERROR_CREATING_GDI_DESKTOP_FONT 368
#define IDS_TO_FREE_UP_SOME_MEMORY_RESTART_WINAMP_THEN_GO_TO_CONFIG 368
#define IDS_ERROR_CREATING_DESKTOP_FONT 369
#define IDS_TO_FREE_UP_VIDEO_MEMORY     369
#define IDS_ERROR_CREATING_TEXTURE_FOR_ICON_BITMAPS 370
#define IDS_MILKDROP_SUGGESTION         370
#define IDS_OUTDATED_VMS_DESKTOP_DLL_NEED_TO_REINSTALL 371
#define IDS_DIRECTX_MISSING_OR_CORRUPT  371
#define IDS_ERROR_CREATING_HOOK_PROC_DESKTOP_ICONS_NOT_AVAILABLE 372
#define IDS_ERROR_THE_PLUGIN_IS_ALREADY_RUNNING 372
#define IDS_ERROR_UPDATING_ICON_BITMAPS 373
#define IDS_UNABLE_TO_READ_DATA_FILE_X  373
#define IDS_ERROR_UPDATING_ICON_BITMAPS_TOO_MANY_UNIQUE_ICON_BITMAPS 374
#define IDS_COULD_NOT_CREATE_MY_VERTEX_DECLARATION 374
#define IDS_ERROR_UPDATING_ICON_BITMAPS_COULD_NOT_GET_LEVEL_DESCRIPTION 375
#define IDS_COULD_NOT_CREATE_WF_VERTEX_DECLARATION 375
#define IDS_ERROR_UPDATING_ICON_BITMAPS_LOCKRECT_FAILED 376
#define IDS_COULD_NOT_CREATE_SPRITE_VERTEX_DECLARATION 376
#define IDS_ERROR_UPDATING_ICON_BITMAPS_LR_PBITS_IS_NULL 377
#define IDS_SHADER_MODEL_X              377
#define IDS_ERROR_UPDATING_ICON_BITMAPS_UNKNOWN_PIXEL_FORMAT 378
#define IDS_UKNOWN_CASE_X               378
#define IDS_ERROR_UPDATING_ICON_BITMAPS_COULDNT_GET_HDC 379
#define IDS_FAILED_TO_COMPILE_PIXEL_SHADERS_USING_X 379
#define IDS_ERROR_UPDATING_ICON_BITMAPS_CALL_TO_GETDIBITS_FAILED 380
#define IDS_FAILED_TO_COMPILE_PIXEL_SHADERS_HARDWARE_MIS_REPORT 380
#define IDS_ERROR_UPDATING_ICON_BITMAPS_CALL_2_TO_GETDIBITS_FAILED 381
#define IDS_COULD_NOT_COMPILE_FALLBACK_WV_SHADER 381
#define IDS_ERROR_UPDATING_ICON_BITMAPS_GETICONINFO_FAILED 382
#define IDS_COULD_NOT_COMPILE_FALLBACK_CV_SHADER 382
#define IDS_ERROR_UPDATING_ICON_BITMAPS_SHGETFILEINFO_FAILED 383
#define IDS_COULD_NOT_COMPILE_FALLBACK_CP_SHADER 383
#define IDS_COULD_NOT_COMPILE_BLUR1_VERTEX_SHADER 384
#define IDS_COULD_NOT_COMPILE_BLUR1_PIXEL_SHADER 385
#define IDS_COULD_NOT_COMPILE_BLUR2_VERTEX_SHADER 386
#define IDS_COULD_NOT_COMPILE_BLUR2_PIXEL_SHADER 387
#define IDS_COULD_NOT_CREATE_INTERNAL_CANVAS_TEXTURE_SMALLER_DISPLAY 388
#define IDS_COULD_NOT_CREATE_INTERNAL_CANVAS_TEXTURE_NOT_ENOUGH_VID_MEM_RECOMMENDATION 389
#define IDS_COULD_NOT_CREATE_INTERNAL_CANVAS_TEXTURE_NOT_ENOUGH_VID_MEM 390
#define IDS_SUCCESSFULLY_CREATED_VS0_VS1 391
#define IDS_ERROR_CREATING_BLUR_TEXTURES 392
#define IDS_COULD_NOT_CREATE_NOISE_TEXTURE 393
#define IDS_COULD_NOT_LOCK_NOISE_TEXTURE 394
#define IDS_NOISE_TEXTURE_BYTE_LAYOUT_NOT_RECOGNISED 395
#define IDS_COULD_NOT_CREATE_3D_NOISE_TEXTURE 396
#define IDS_COULD_NOT_LOCK_3D_NOISE_TEXTURE 397
#define IDS_3D_NOISE_TEXTURE_BYTE_LAYOUT_NOT_RECOGNISED 398
#define IDS_ERROR_CREATING_SHADER       399
#define IDS_PLEASE_EXIT_VIS_BEFORE_RUNNING_CONFIG_PANEL 400
#define IDS_FPS                         401
#define IDS_PF_MONITOR                  402
#define IDS_PRESS_F9_TO_HIDE_SHADER_QREF 403
#define IDS_PRESS_F9_TO_SHOW_SHADER_QREF 404
#define IDS_WARP_AND_COMPOSITE_SHADERS_LOCKED 405
#define IDS_WARP_SHADER_LOCKED          406
#define IDS_COMPOSITE_SHADER_LOCKED     407
#define IDS_PRESET_USES_HIGHEST_PIXEL_SHADER_VERSION 408
#define IDS_PRESET_HAS_MIXED_VERSIONS_OF_SHADERS 409
#define IDS_PRESET_DOES_NOT_USE_PIXEL_SHADERS 410
#define IDS_TO_FREE_UP_VIDEO_MEMORY_2   411
#define IDS_WARNING_OLD_GPU_MIGHT_NOT_WORK_WITH_PRESET 411
#define IDS_PRESET_CURRENTLY_USES_PS_X  412
#define IDS_WARNING_DO_NOT_FORGET_WARP_SHADER_WAS_LOCKED 413
#define IDS_WARNING_DO_NOT_FORGET_COMPOSITE_SHADER_WAS_LOCKED 414
#define IDS_THIS_PLUGIN_NEEDS_MUSIC_TO_RUN 415
#define IDS_PRESET_MASH_UP_TEXT1        415
#define IDS_NO_MUSIC_PLAYING            416
#define IDS_PRESET_MASH_UP_TEXT2        416
#define IDS_PRESET_MASH_UP_TEXT3        417
#define IDS_PRESET_MASH_UP_TEXT4        418
#define IDS_UPGRADE_TO_USE_PS_X         419
#define IDS_DIRECTORY_OF_X              420
#define IDS_SHADER_MODEL_2              421
#define IDS_SHUFFLE_IS_NOW_OFF          421
#define IDS_SHADER_MODEL_3              422
#define IDS_SHUFFLE_IS_NOW_ON           422
#define IDS_SHADER_MODEL_4              423
#define IDS_COMPSHADER_LOCKED           423
#define IDS_WARPSHADER_LOCKED           424
#define IDS_ALLSHADERS_LOCKED           425
#define IDS_ALLSHADERS_UNLOCKED         426
#define IDS_PS_AUTO_RECOMMENDED         427
#define IDS_PS_DISABLED                 428
#define IDS_PS_SHADER_MODEL_2           429
#define IDS_PS_SHADER_MODEL_3           430
#define IDS_TX_8_BITS_PER_CHANNEL       431
#define IDS_TX_16_BITS_PER_CHANNEL      432
#define IDS_TX_32_BITS_PER_CHANNEL      433
#define IDS_160X120_SLOW                434
#define IDS_192X144_SLOW                435
#define IDS_NONE_BEST_IMAGE_QUALITY     436
#define IDS_1_25_X                      437
#define IDS_1_33_X                      438
#define IDS_1_5_X                       439
#define IDS_1_67_X                      440
#define IDS_2_X                         441
#define IDS_3_X                         442
#define IDS_4_X                         443
#define IDS_NEAREST_POWER_OF_2          444
#define IDS_EXACT_RECOMMENDED           445
#define IDS_PIXEL_SHADERS               446
#define IDS_PIXEL_SHADERS_TEXT          447
#define IDS_TEXFORMAT                   448
#define IDS_TEXFORMAT_TEXT              449
#define IDS_CANVAS_SIZE                 450
#define IDS_CANVAS_SIZE_TEXT            451
#define IDS_CANVAS_STRETCH              452
#define IDS_CANVAS_STRETCH_TEXT         453
#define IDS_MAX_IMAGES_BYTES_TEXT       454
#define IDS_MENU_EDIT_WARP_SHADER       455
#define IDS_UPGRADE_SHADERS_TO_USE_PS2  456
#define IDS_MENU_EDIT_COMPOSITE_SHADER  456
#define IDS_UPGRADE_SHADERS_TO_USE_PS3  457
#define IDS_MENU_BLUR1_EDGE_DARKEN_AMOUNT 457
#define IDS_MENU_BLUR1_EDGE_DARKEN_AMOUNT_TT 458
#define IDS_UPGRADE_TO_USE_PS2          459
#define IDS_MENU_BLUR1_MIN_COLOR_VALUE  459
#define IDS_MENU_BLUR1_MIN_MAX_COLOR_VALUE_TT 460
#define IDS_PRESET_CURRENTLY_USES_PS2   461
#define IDS_MENU_BLUR1_MAX_COLOR_VALUE  461
#define IDS_UPGRADE_TO_USE_PS3          462
#define IDS_MENU_BLUR2_MIN_COLOR_VALUE  462
#define IDS_PRESET_CURRENTLY_USES_PS3   463
#define IDS_MENU_BLUR2_MIN_MAX_COLOR_VALUE_TT 463
#define IDS_UPGRADE_TO_USE_PS4          464
#define IDS_MENU_BLUR2_MAX_COLOR_VALUE  464
#define IDS_MENU_BLUR3_MIN_COLOR_VALUE  465
#define IDS_MENU_BLUR3_MIN_MAX_COLOR_VALUE_TT 466
#define IDS_MENU_BLUR3_MAX_COLOR_VALUE  467
#define IDS_PRESET_CURRENTLY_USES_PS2X  468
#define IDS_MENU_EDIT_PER_VERTEX_EQUATIONS 468
#define IDS_UPGRADE_TO_USE_PS2X         469
#define IDS_MENU_EDIT_PER_VERTEX_EQUATIONS_TT 469
#define IDS_MENU_EDIT_WARP_SHADER_TT    470
#define IDS_MENU_EDIT_COMPOSITE_SHADER_TT 471
#define IDS_MENU_EDIT_UPGRADE_PRESET_PS_VERSION 472
#define IDS_MENU_EDIT_UPGRADE_PRESET_PS_VERSION_TT 473
#define IDS_MENU_EDIT_DO_A_PRESET_MASH_UP 474
#define IDS_MENU_EDIT_DO_A_PRESET_MASH_UP_TT 475
#define IDS_MENU_NUMBER_OF_INSTANCES    476
#define IDS_MENU_NUMBER_OF_INSTANCES_TT 477
#define IDS_MENU_EDIT_INIT_CODE_SHAPE_TT 478
#define IDS_MENU_EDIT_PER_FRAME_INSTANCE_CODE 479
#define IDS_MENU_EDIT_PER_FRAME_INSTANCE_CODE_TT 480
#define IDS_ERROR_PRESET_NOT_FOUND_X    481
#define IDS_ERROR_NO_PRESET_FILES_OR_DIRS_FOUND_IN_X 482
#define IDS_SCANNING_PRESETS            483
#define IDS_SPRITE_X_ERROR_COULD_NOT_FIND_IMG_OR_NOT_DEFINED 484
#define IDS_WARNING_PRESET_X_ERROR_IN_PRESET_INIT_CODE 485
#define IDS_WARNING_PRESET_X_ERROR_IN_PER_FRAME_CODE 486
#define IDS_WARNING_PRESET_X_ERROR_IN_PER_VERTEX_CODE 487
#define IDS_HZ                          488
#define IDS_HELP_MINIMIZE_WINAMP        489
#define IDS_HELP_MINIMIZE_WINAMP_HELP   490
#define IDS_DIRECTX_MISSING_OR_CORRUPT_TEXT 491
#define IDS_PARENT_DIRECTORY            492
#define IDS_RAND_TITLE                  493
#define IDS_RAND_MSG                    494
#define IDS_MAX_IMAGES_BYTES            495
#define IDS_PAGE_X                      496
#define IDS_MB                          497
#define IDS_GB                          498
#define IDS_MASHUP_GENERAL_POSTPROC     499
#define IDS_MASHUP_MOTION_EQUATIONS     500
#define IDS_MASHUP_WAVEFORMS_SHAPES     501
#define IDS_MASHUP_WARP_SHADER          502
#define IDS_MASHUP_COMP_SHADER          503
#define IDS_STRING615                   504
#define IDS_STRING616                   505
#define IDS_STRING617                   506
#define IDS_STRING618                   507
#define IDS_STRING619                   508
#define IDS_STRING620                   509
#define IDS_STRING621                   510
#define IDS_STRING622                   511
#define IDS_STRING623                   512
#define IDS_MENU_BLUR1_MIN_COLOR_VALUE_TT 513
#define IDS_STRING624                   513
#define IDS_STRING625                   514
#define IDS_MENU_BLUR1_MAX_COLOR_VALUE_TT 515
#define IDS_STRING626                   515
#define IDS_STRING627                   516
#define IDS_MENU_BLUR2_MIN_COLOR_VALUE_TT 517
#define IDS_STRING628                   517
#define IDS_STRING629                   518
#define IDS_MENU_BLUR2_MAX_COLOR_VALUE_TT 519
#define IDS_STRING630                   519
#define IDS_STRING631                   520
#define IDS_MENU_BLUR3_MIN_COLOR_VALUE_TT 521
#define IDS_STRING632                   521
#define IDS_STRING633                   522
#define IDS_MENU_BLUR3_MAX_COLOR_VALUE_TT 523
#define IDS_STRING634                   523
#define IDS_STRING635                   524
#define IDS_UPGRADE_SHADERS_TO_USE_PS_X 525
#define IDS_PRESS_ESC_TO_RETURN         526
#define IDS_COULD_NOT_LOAD_TEXTURE_X    527
#define IDS_ERROR_COMPILING_X_X_SHADER  528
#define IDS_ERROR_PARSING_X_X_SHADER    529
#define IDS_UNABLE_TO_RESOLVE_TEXSIZE_FOR_A_TEXTURE_NOT_IN_USE 530
#define IDS_KEY_MAPPINGS                531
#define IDS_DIRECTX_INSTALL_ISSUE       532
#define IDS_DIRECTX_INSTALL_FAILED      533
#define IDS_DIRECTX_INSTALL_SUCCEEDED   534
#define IDS_UPGRADE_SHADERS_TO_USE_PS2X 581
#define IDC_CB_FOG                      1000
#define IDC_CB_SUPERTEX                 1001
#define IDC_CB_HELP_MSG                 1001
#define IDC_CB_PRESS_F1_MSG             1001
#define IDC_DISP_MODE                   1003
#define IDC_CB_FS                       1004
#define IDC_CB_PT                       1005
#define IDC_CB_WPT                      1005
#define IDC_SZ_ABOUT                    1006
#define IDC_CB_MIN                      1006
#define IDC_ADAPTER_W                   1007
#define IDC_ADAPTER_TEXT                1008
#define IDC_ADAPTER_W_CAPTION           1008
#define IDC_ADAPTER_FFS                 1008
#define IDC_ADAPTER_DMS                 1008
#define IDC_DISP_MODE_TEXT              1009
#define IDC_DISP_MODE_CAPTION           1009
#define IDC_ADAPTER_FS                  1010
#define IDC_ADAPTER_TEXT2               1011
#define IDC_ADAPTER_FS_CAPTION          1011
#define IDC_FS_ADAPTER_CAPTION          1011
#define IDC_CB_TWOPASS                  1012
#define IDC_CB_FFSPT                    1012
#define IDC_CB_DMSPT                    1012
#define IDC_CB_TRANS_HAIR               1013
#define IDC_ADAPTER_FS_CAPTION2         1013
#define IDC_W_ADAPTER_CAPTION           1013
#define IDC_FONT2b                      1013
#define IDC_FONT2                       1013
#define IDC_CB_3B                       1014
#define IDC_ADD_STUFF_HERE              1014
#define IDC_FFS_ADAPTER_CAPTION         1014
#define IDC_DMS_ADAPTER_CAPTION         1014
#define IDC_CB_DEBUGOUTPUT              1014
#define IDC_FONT3b                      1014
#define IDC_FONT3                       1014
#define IDC_MQ                          1015
#define IDC_CB_FAKE                     1015
#define IDC_TEXSIZECOMBO                1015
#define IDC_FONT4b                      1015
#define IDC_FONT4                       1015
#define IDC_DISP_MODE_TEXT2             1016
#define IDC_CB_NO_FAKE_TIPS             1016
#define IDC_TAB1                        1016
#define IDC_TABS                        1016
#define IDC_CB_FSPT                     1016
#define IDC_FONTSIZE                    1016
#define IDC_CB_AUTOGAMMA                1016
#define IDC_FONT5b                      1016
#define IDC_FONT5                       1016
#define IDC_WMS                         1017
#define IDC_MESHSIZECOMBO               1017
#define IDC_FONTSIZE3                   1017
#define IDC_DISP_MODE_TEXT3             1018
#define IDC_MULTISAMPLING_CAPTION2      1018
#define IDC_FS_BOX                      1018
#define IDC_W_MULTISAMPLING_CAPTION     1018
#define IDC_BETWEEN_TIME                1018
#define IDC_FONTSIZE4                   1018
#define IDC_FSMS                        1019
#define IDC_CB_ALWAYS3D                 1019
#define IDC_BETWEEN_TIME_RANDOM         1019
#define IDC_FONT6b                      1019
#define IDC_FONT6                       1019
#define IDC_DISP_MODE_TEXT4             1020
#define IDC_MULTISAMPLING_CAPTION       1020
#define IDC_FRACTAL_RES_CAPTION         1020
#define IDC_INITIAL_WAVEMODE_CAPTION    1020
#define IDC_CB_DMS                      1020
#define IDC_HARDCUT_BETWEEN_TIME        1020
#define IDC_FONTSIZE5                   1020
#define IDC_CB_SCROLLON                 1020
#define IDC_FS_LIMIT                    1021
#define IDC_FS_MAXFPS                   1021
#define IDC_FONTOPTIONS                 1021
#define IDC_TEXFORMAT                   1021
#define IDC_DISP_MODE_TEXT5             1022
#define IDC_FRAME_DELAY_CAPTION         1022
#define IDC_FS_FRAME_DELAY_CAPTION      1022
#define IDC_FS_MAXFPS_CAPTION           1022
#define IDC_FONTOPTIONS3                1022
#define IDC_SHADERS                     1022
#define IDC_W_LIMIT                     1023
#define IDC_W_MAXFPS                    1023
#define IDC_CB_NOWARN                   1023
#define IDC_BLEND_AUTO                  1023
#define IDC_CB_SCROLLON2                1023
#define IDC_DISP_MODE_TEXT6             1024
#define IDC_FRAME_DELAY_CAPTION2        1024
#define IDC_G_BOX                       1024
#define IDC_W_FRAME_DELAY_CAPTION       1024
#define IDC_W_MAXFPS_CAPTION            1024
#define IDC_CB_NOWARN2                  1024
#define IDC_BLEND_USER                  1024
#define IDC_W_BOX                       1025
#define IDC_CB_SAVE_CPU                 1025
#define IDC_FONT7b                      1025
#define IDC_FONT7                       1025
#define IDC_CB_ANISO                    1025
#define IDC_TABS_PLACEHOLDER            1026
#define IDC_FFSMS                       1026
#define IDC_DMSMS                       1026
#define IDC_CB_NORATING                 1026
#define IDC_MULTISAMPLING_CAPTION3      1027
#define IDC_FFS_MULTISAMPLING_CAPTION   1027
#define IDC_FONTSIZE2                   1027
#define IDC_DMS_MULTISAMPLING_CAPTION   1027
#define IDC_CB_INSTASCAN                1027
#define IDC_FRAME_DELAY_CAPTION3        1028
#define IDC_FFS_FRAME_DELAY_CAPTION     1028
#define IDC_FFS_MAXFPS_CAPTION          1028
#define IDC_FONTOPTIONS2                1028
#define IDC_DMS_MAXFPS_CAPTION          1028
#define IDC_STRETCH                     1028
#define IDC_FFS_LIMIT                   1029
#define IDC_FFS_MAXFPS                  1029
#define IDC_DMS_MAXFPS                  1029
#define IDC_FONTSIZE6                   1029
#define IDC_MAX_IMAGES                  1029
#define IDC_RECT                        1030
#define IDC_CB_SKIN                     1030
#define IDC_MAX_BYTES                   1030
#define IDC_Q                           1031
#define IDC_FRACTAL_RES                 1031
#define IDC_INITIAL_WAVEMODE            1031
#define IDC_FONT8b                      1031
#define IDC_FONT8                       1031
#define IDC_CB_MIN2                     1031
#define IDC_CB_FIXSLOWTEXT              1031
#define IDC_HS_ANIM_SPEED               1032
#define IDC_BETWEEN_TIME_LABEL          1032
#define IDC_FONTSIZE7                   1032
#define IDC_CB_FIXSLOWTEXT2             1032
#define IDC_CB_RECURSE                  1032
#define IDC_FS_MULTISAMPLING_CAPTION    1033
#define IDC_BETWEEN_TIME_RANDOM_LABEL   1033
#define IDC_HS_ANIM_SPEED_CAPTION       1034
#define IDC_BLEND_AUTO_LABEL            1034
#define IDC_FONT9b                      1034
#define IDC_FONT9                       1034
#define IDC_BLEND_USER_LABEL            1035
#define IDC_FONTSIZE8                   1035
#define IDC_FFS_LABEL                   1036
#define IDC_DMS_LABEL                   1036
#define IDC_BLEND_USER_LABEL2           1036
#define IDC_BETWEEN_TIME_LABEL2         1036
#define IDC_RAND_TITLE_LABEL            1036
#define IDC_HARDCUT_BETWEEN_TIME_LABEL  1036
#define IDC_FS_LABEL                    1037
#define IDC_BLEND_USER_LABEL3           1037
#define IDC_RAND_MSG_LABEL              1037
#define IDC_W_LABEL                     1038
#define IDC_FONTSIZE9                   1038
#define IDC_3DSEP_LABEL                 1038
#define ID_FONTS                        1039
#define IDC_BRIGHT_SLIDER               1039
#define IDC_FONT_CAPTION                1040
#define ID_DM_MORE                      1040
#define IDC_FONTSIZE_CAPTION            1041
#define ID_DUALHEAD                     1041
#define IDC_FONTOPTIONS_CAPTION         1042
#define IDC_SYSTEM_FONT                 1043
#define IDC_CB_SEPTEXT                  1043
#define IDC_FONT_NAME_2                 1043
#define IDC_DECORATIVE_FONT             1044
#define IDC_HARDCUT_LOUDNESS            1044
#define IDC_FONT_NAME_1                 1044
#define IDC_CB_HARDCUTS                 1045
#define IDC_TITLE_FONT                  1045
#define IDC_FONT_NAME_3                 1045
#define IDC_CB_BOX                      1046
#define IDC_SONGTITLEANIM_DURATION      1046
#define IDC_FONT_NAME_4                 1046
#define IDC_DM_ALPHA_FIX                1047
#define IDC_CB_TITLE_ANIMS              1047
#define IDC_FONT_NAME_5                 1047
#define IDC_DM_ALPHA_FIX_CAPTION        1048
#define IDC_V_PICK                      1048
#define IDC_RAND_TITLE                  1048
#define IDC_FONT_NAME_6                 1048
#define IDC_CB_MANUAL_SCOOT             1049
#define IDC_T1                          1049
#define IDC_RAND_MSG                    1049
#define IDC_FONT_NAME_7                 1049
#define IDC_T3                          1050
#define IDC_CB_SHOW_ICONS               1050
#define IDC_FONT_NAME_8                 1050
#define IDC_3DSEP                       1050
#define IDC_H_PICK                      1051
#define IDC_T5                          1051
#define IDC_FONT_NAME_9                 1051
#define IDC_T2                          1052
#define IDC_FONTOPTIONS_CAPTION2        1052
#define IDC_T4                          1053
#define IDC_FONTOPTIONS_CAPTION3        1053
#define IDC_FONT_TEXT                   1054
#define IDC_TEXSIZECOMBO_CAPTION        1054
#define IDC_MESHSIZECOMBO_CAPTION       1055
#define IDC_BRIGHT_SLIDER_BOX           1056
#define IDC_SONGTITLEANIM_DURATION_LABEL 1057
#define IDC_TEXFORMAT_CAPTION           1057
#define IDC_HARDCUT_LOUDNESS_LABEL      1058
#define IDC_SHADERS_CAPTION             1058
#define IDC_FONTSIZE1                   1059
#define IDC_HARDCUT_LOUDNESS_MIN        1059
#define IDC_BRIGHT_SLIDER_BOX2          1059
#define IDC_HARDCUT_LOUDNESS_MAX        1060
#define IDC_STRETCH_CAPTION             1060
#define IDC_CB_VJMODE                   1061
#define IDC_MAX_IMAGES_CAPTION          1061
#define IDC_MAX_BYTES_CAPTION           1062
#define IDC_FONTBOLD1                   1063
#define IDC_FONTITAL1                   1064
#define IDC_FONTAA1                     1065
#define IDC_FONTBOLD2                   1066
#define IDC_FONTITAL2                   1067
#define IDC_FONTAA2                     1068
#define IDC_FONTBOLD3                   1069
#define IDC_FONTITAL3                   1070
#define IDC_FONTAA3                     1071
#define IDC_FONTBOLD4                   1072
#define IDC_FONTITAL4                   1073
#define IDC_FONTAA4                     1074
#define IDC_FONTBOLD5                   1075
#define IDC_FONTITAL5                   1076
#define IDC_FONTAA5                     1077
#define IDC_FONTBOLD6                   1078
#define IDC_FONTITAL6                   1079
#define IDC_FONTAA6                     1080
#define IDC_FONTBOLD7                   1084
#define IDC_FONTITAL7                   1085
#define IDC_FONTAA7                     1086
#define IDC_FONTBOLD8                   1087
#define IDC_FONTITAL8                   1088
#define IDC_FONTAA8                     1089
#define IDC_FONTBOLD9                   1090
#define IDC_FONTITAL9                   1091
#define IDC_FONTAA9                     1092
#define IDC_FONT1b                      1093
#define IDC_FONT1                       1093
#define ID_QUIT                         40006
#define ID_GO_FS                        40007
#define ID_SHOWHELP                     40008
#define ID_SHOWPLAYLIST                 40009
#define ID_DESKTOP_MODE                 40010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
